services:
  pocketbase:
    image: adrianmusante/pocketbase:latest
    restart: unless-stopped
    environment:
      POCKETBASE_ADMIN_EMAIL: ${POCKETBASE_ADMIN_EMAIL}
      POCKETBASE_ADMIN_PASSWORD: ${POCKETBASE_ADMIN_PASSWORD}
      POCKETBASE_ADMIN_UPSERT: "true"
    ports:
      - "${PORT}:8090"
    volumes:
      - pocketbase:/pocketbase
volumes:
  pocketbase:
