services:
  meilisearch:
    image: getmeili/meilisearch:v1.10
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MASTER_KEY}
      MEILI_ENV: production
    ports:
      - "${PORT}:7700"
    volumes:
      - meilidata:/meili_data
volumes:
  meilidata:
