services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "${PORT}:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
volumes:
  mariadbdata:
